apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-argo-application
  namespace: argocd
  annotations:
    # notifications.argoproj.io/subscribe.on-sync-succeeded.slack: devops-internship-alerts
    # notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: devops-internship-alerts
    # notifications.argoproj.io/subscribe.on-sync-failed.slack: devops-internship-alerts
    # notifications.argoproj.io/subscribe.on-health-degraded.slack: devops-internship-alerts
    # notifications.argoproj.io/subscribe.on-deployed.slack: devops-internship-alerts
    # notifications.argoproj.io/subscribe.on-deleted.slack: devops-internship-alerts
    # notifications.argoproj.io/subscribe.on-created.slack: devops-internship-alerts
    argocd-image-updater.argoproj.io/image-list: prod-argo-application=docker.io/vovka7surnyk/task-01
    argocd-image-updater.argoproj.io/prod-argo-application.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/prod-argo-application.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/prod-argo-application.allow-tags: regexp:^stg-\d{1,2}\.\d{1,2}\.\d{1,2}$
    argocd-image-updater.argoproj.io/prod-argo-application.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: HEAD
    argocd-image-updater.argoproj.io/prod-argo-application.force-update: "true"
    # argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  project: default
  source:
    chart: Chart-task-01
    helm:
      valueFiles:
          - values.yaml
      values: |
        image:
          tag: 0.0.10

    repoURL: https://gitlab.com/api/v4/projects/40594299/packages/helm/stable
    targetRevision: 0.1.0


  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true




