# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ .Release.Name }}-nginx-ingress
#   labels:
#     name: {{ .Release.Name }}-nginx-ingress
#   # namespace: app
# {{- if .Values.ingress.annotations }}
#   annotations:
# {{ toYaml .Values.ingress.annotations | indent 4 }}
# {{- end }}
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: {{ .Values.ingress.rules.host }}
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: {{ .Release.Name }}-service
#             port: 
#               number: {{ .Values.service.ports.port }}
#   tls:
#   - hosts:
#     - {{ .Values.ingress.rules.host }}
#     secretName: test-ingress-app-production