apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
- ClusterIssuer.yaml
images:
- name: docker.io/vovka7surnyk/task-01
  newTag: 0.0.7
